// In-browser port of scripts/generate_shortcut.py: builds the exact same
// "Sync Health Data" iOS Shortcut action graph and serializes it to the same
// bytes plistlib.dump(..., fmt=FMT_XML) would produce for the same inputs.
// Golden-tested against a fixture generated by that script — see
// web/test/shortcut.test.ts and web/test/fixtures/golden.shortcut.
//
// Two things had to be reverse-engineered from the python side to make byte
// parity possible:
//   1. plistlib.dump's default `sort_keys=True` means every dict's keys are
//      written in sorted order, not source order — writeDict below sorts too.
//   2. The python generator's UUIDs come from `uuid.uuid4()`, which is random
//      per run — there is no way to byte-match that from here. `buildWorkflow`
//      takes an injectable `uuidGen` so the golden test can supply the same
//      deterministic sequence used to produce the fixture; `buildShortcut`
//      (the real entry point) uses `crypto.randomUUID()` like a normal run.

export type PlistValue = string | number | boolean | PlistValue[] | PlistDict;
export type PlistDict = { [key: string]: PlistValue };

// U+FFFC OBJECT REPLACEMENT CHARACTER — matches generate_shortcut.py's
// PLACEHOLDER, standing in for each attachment (magic variable chip) inside
// a WFTextTokenString's "string" field.
const PLACEHOLDER = "￼";

// (iOS Health picker label, server metric name, unit health-mcp expects, statistic)
const METRICS: Array<[label: string, metric: string, unit: string, stat: string]> = [
	["Dietary Calories", "calories", "kcal", "Sum"],
	["Protein", "protein", "g", "Sum"],
	["Carbohydrates", "carbs", "g", "Sum"],
	["Total Fat", "fat", "g", "Sum"],
	["Water", "water", "floz", "Sum"],
	["Sodium", "sodium", "mg", "Sum"],
	["Weight", "weight", "lb", "Average"],
	["Body Fat Percentage", "body_fat_pct", "%", "Average"],
];

function actionOutput(outputUuid: string, name: string): PlistDict {
	return { OutputUUID: outputUuid, OutputName: name, Type: "ActionOutput" };
}

function attachment(value: PlistDict): PlistDict {
	return { Value: value, WFSerializationType: "WFTextTokenAttachment" };
}

function act(identifier: string, params: PlistDict): PlistDict {
	return { WFWorkflowActionIdentifier: identifier, WFWorkflowActionParameters: params };
}

/** WFTextTokenString from a list of string parts / attachment(...) dicts. */
function tokenString(parts: Array<string | PlistDict>): PlistDict {
	let s = "";
	const attachments: PlistDict = {};
	for (const p of parts) {
		if (typeof p === "string") {
			s += p;
			continue;
		}
		// Inside attachmentsByRange the reference is bare — the WFTextTokenAttachment
		// envelope is only for standalone parameters (mirrors the python comment).
		const bare = p.WFSerializationType === "WFTextTokenAttachment" ? (p.Value as PlistDict) : p;
		attachments[`{${s.length}, 1}`] = bare;
		s += PLACEHOLDER;
	}
	const value: PlistDict = { string: s };
	if (Object.keys(attachments).length > 0) value.attachmentsByRange = attachments;
	return { Value: value, WFSerializationType: "WFTextTokenString" };
}

/** Device-verified filter: locked Type row + "Start Date is <Adjusted Date output>". */
function healthFilter(sampleType: string, dateUuid: string): PlistDict {
	return {
		Value: {
			WFActionParameterFilterPrefix: 1,
			WFActionParameterFilterTemplates: [
				{
					Bounded: true,
					Operator: 4,
					Property: "Type",
					Removable: false,
					Values: {
						Enumeration: { Value: sampleType, WFSerializationType: "WFStringSubstitutableState" },
					},
				},
				{
					Bounded: true,
					Operator: 4,
					Property: "Start Date",
					Removable: false,
					Values: {
						Date: attachment(actionOutput(dateUuid, "Adjusted Date")),
						// Vestigial fields present in a device's own export:
						Number: "7",
						Unit: 16,
					},
				},
			],
			WFContentPredicateBoundedDate: false,
		},
		WFSerializationType: "WFContentPredicateTableTemplate",
	};
}

/** Builds the workflow dict (pre-serialization). `uuidGen` is called once per
 * identifier, in the exact order generate_shortcut.py's `build()` calls
 * `u()` — the golden test supplies a deterministic generator to reproduce
 * the fixture; `buildShortcut` below supplies `crypto.randomUUID`. */
export function buildWorkflow(url: string, key: string, uuidGen: () => string): PlistDict {
	const loopGroup = uuidGen();
	const adjUuid = uuidGen();
	const fmtUuid = uuidGen();

	const actions: PlistDict[] = [
		act("is.workflow.actions.repeat.count", {
			GroupingIdentifier: loopGroup,
			WFControlFlowMode: 0,
			WFRepeatCount: 3,
		}),
		// Adjusted Date = Current Date - Repeat Index days (iteration 1 = yesterday).
		act("is.workflow.actions.adjustdate", {
			UUID: adjUuid,
			WFDate: tokenString([attachment({ Type: "CurrentDate" })]),
			WFAdjustOperation: "Subtract",
			WFDuration: {
				Value: { Magnitude: { Type: "Variable", VariableName: "Repeat Index" }, Unit: "days" },
				WFSerializationType: "WFQuantityFieldValue",
			},
		}),
		act("is.workflow.actions.format.date", {
			UUID: fmtUuid,
			WFDate: tokenString([attachment(actionOutput(adjUuid, "Adjusted Date"))]),
			WFDateFormatStyle: "Custom",
			WFDateFormat: "yyyy-MM-dd",
		}),
	];

	const parts: Array<string | PlistDict> = ['{"entries": ['];
	const statUuids: string[] = [];
	for (const [label, , , stat] of METRICS) {
		const findUuid = uuidGen();
		const statUuid = uuidGen();
		actions.push(
			act("is.workflow.actions.filter.health.quantity", {
				UUID: findUuid,
				WFContentItemFilter: healthFilter(label, adjUuid),
			}),
		);
		actions.push(
			act("is.workflow.actions.statistics", {
				UUID: statUuid,
				Input: attachment(actionOutput(findUuid, "Health Samples")),
				WFStatisticsOperation: stat,
			}),
		);
		statUuids.push(statUuid);
	}

	let first = true;
	METRICS.forEach(([, metric, unit, stat], i) => {
		const statUuid = statUuids[i];
		if (!first) parts.push(", ");
		first = false;
		parts.push(
			'{"date": "',
			attachment(actionOutput(fmtUuid, "Formatted Date")),
			'", "metric": "',
			metric,
			'", "value": "',
			attachment(actionOutput(statUuid, stat)),
			'", "unit": "',
			unit,
			'", "source": "shortcut"}',
		);
	});
	parts.push("]}");

	const bodyUuid = uuidGen();
	const postUuid = uuidGen();
	actions.push(
		act("is.workflow.actions.gettext", {
			UUID: bodyUuid,
			WFTextActionText: tokenString(parts),
		}),
	);
	actions.push(
		act("is.workflow.actions.downloadurl", {
			UUID: postUuid,
			Advanced: true,
			ShowHeaders: true,
			WFURL: url,
			WFHTTPMethod: "POST",
			WFHTTPBodyType: "File",
			WFRequestVariable: attachment(actionOutput(bodyUuid, "Text")),
			WFHTTPHeaders: {
				Value: {
					WFDictionaryFieldValueItems: [
						{ WFItemType: 0, WFKey: tokenString(["X-Api-Key"]), WFValue: tokenString([key]) },
						{ WFItemType: 0, WFKey: tokenString(["Content-Type"]), WFValue: tokenString(["application/json"]) },
					],
				},
				WFSerializationType: "WFDictionaryFieldValue",
			},
		}),
	);
	// Shows each day's server response on manual runs — delete this one action
	// before enabling the daily automation (per docs/shortcut.md).
	actions.push(
		act("is.workflow.actions.showresult", {
			UUID: uuidGen(),
			Text: tokenString([attachment(actionOutput(postUuid, "Contents of URL"))]),
		}),
	);
	actions.push(
		act("is.workflow.actions.repeat.count", {
			UUID: uuidGen(),
			GroupingIdentifier: loopGroup,
			WFControlFlowMode: 2,
		}),
	);

	return {
		WFWorkflowActions: actions,
		WFWorkflowClientVersion: "4610.1",
		WFWorkflowMinimumClientVersion: 900,
		WFWorkflowMinimumClientVersionString: "900",
		WFWorkflowIcon: { WFWorkflowIconGlyphNumber: 61440, WFWorkflowIconStartColor: -43634177 },
		WFWorkflowName: "Sync Health Data",
		WFWorkflowImportQuestions: [],
		WFWorkflowTypes: [],
		WFQuickActionSurfaces: [],
		WFWorkflowInputContentItemClasses: [],
		WFWorkflowOutputContentItemClasses: [],
		WFWorkflowHasOutputFallback: false,
		WFWorkflowHasShortcutInputVariables: false,
	};
}

const PLIST_HEADER =
	'<?xml version="1.0" encoding="UTF-8"?>\n' +
	'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n';

// Mirrors plistlib._escape: only '&', '<', '>' are escaped in XML text
// content (quotes are left bare — valid inside element text, and that's
// what plistlib itself emits).
function escapeXml(text: string): string {
	return text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Re-implements plistlib's `_PlistWriter` (FMT_XML, sort_keys=True, the
 * plistlib.dump default) closely enough to reproduce its output byte for
 * byte: tab indentation, sorted dict keys, self-closing empty containers. */
class PlistXmlWriter {
	private lines: string[] = [];
	private indentLevel = 0;

	private writeln(line: string): void {
		this.lines.push("\t".repeat(this.indentLevel) + line);
	}

	private simpleElement(element: string, value?: string): void {
		if (value !== undefined) this.writeln(`<${element}>${escapeXml(value)}</${element}>`);
		else this.writeln(`<${element}/>`);
	}

	private beginElement(element: string): void {
		this.writeln(`<${element}>`);
		this.indentLevel++;
	}

	private endElement(element: string): void {
		this.indentLevel--;
		this.writeln(`</${element}>`);
	}

	private writeValue(value: PlistValue): void {
		if (typeof value === "string") {
			this.simpleElement("string", value);
		} else if (value === true) {
			this.simpleElement("true");
		} else if (value === false) {
			this.simpleElement("false");
		} else if (typeof value === "number") {
			if (!Number.isInteger(value)) throw new TypeError(`plist: unsupported non-integer number ${value}`);
			this.simpleElement("integer", String(value));
		} else if (Array.isArray(value)) {
			this.writeArray(value);
		} else if (value && typeof value === "object") {
			this.writeDict(value);
		} else {
			throw new TypeError(`plist: unsupported value ${String(value)}`);
		}
	}

	private writeDict(d: PlistDict): void {
		const keys = Object.keys(d);
		if (keys.length === 0) {
			this.simpleElement("dict");
			return;
		}
		keys.sort();
		this.beginElement("dict");
		for (const key of keys) {
			this.simpleElement("key", key);
			this.writeValue(d[key]);
		}
		this.endElement("dict");
	}

	private writeArray(arr: PlistValue[]): void {
		if (arr.length === 0) {
			this.simpleElement("array");
			return;
		}
		this.beginElement("array");
		for (const v of arr) this.writeValue(v);
		this.endElement("array");
	}

	write(value: PlistDict): string {
		this.writeln('<plist version="1.0">');
		this.writeValue(value);
		this.writeln("</plist>");
		return PLIST_HEADER + this.lines.join("\n") + "\n";
	}
}

export function serializePlist(value: PlistDict): Uint8Array<ArrayBuffer> {
	return new TextEncoder().encode(new PlistXmlWriter().write(value));
}

/** Builds the bytes of a "Sync Health Data.shortcut" file with `ingestUrl`/
 * `ingestKey` baked in — the browser-side equivalent of running
 * `INGEST_URL=... INGEST_KEY=... python3 scripts/generate_shortcut.py`. */
export function buildShortcut(ingestUrl: string, ingestKey: string): Uint8Array<ArrayBuffer> {
	const uuidGen = (): string => crypto.randomUUID().toUpperCase();
	return serializePlist(buildWorkflow(ingestUrl, ingestKey, uuidGen));
}
